name: build_and_release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build_and_release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: build and release gh-gr
    steps:
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: precompile binaries and upload assets
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "scripts/build.sh"
          go_version: ${{ matrix.go }}
