name: build_and_release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build_and_release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: build and release gh-gr
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install upx
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Update gopls
        run: go install golang.org/x/tools/gopls@latest
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run linters
        run: gofmt -s -d ./ && golangci-lint run -v
      - name: Precompile binaries and upload assets
        uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "scripts/build.sh"
          go_version: ${{ matrix.go }}
